### ISSUE TITLE
please export tests

### ISSUE THREAD

**Issue by MeggyCal** [desbma/web_cache#1]
Could you please export the tests/ directory in the release tarball? Thank you.

**Comment by desbma** [comment]
The [release archives](https://github.com/desbma/web_cache/releases) all contain the `tests` directory.

Maybe you have downloaded the `.tar.gz` from the PyPI package?

**Comment by MeggyCal** [comment]
Yes, that is what I did. Why don't you export the tests also in PyPi tarballs?

Anyway, thank you. Now the tests are running correctly.

**Comment by desbma** [comment]
PyPI is mostly used when downloading packages as dependencies for other packages, for example with pip, and in that case end users do not want to have tests cluttering their system.

On the other hand, the release archives or git repository is intended for developers, so tests are in it.
